/**
 * Quality Assurance API Service
 * Handles all API calls for the Quality Assurance & Compliance System
 */

import { apiClient } from '@/services/api/apiClient'

const BASE_URL = '/api/quality-assurance'

export const qualityAssuranceApi = {
  // Dashboard
  getDashboardData: () => apiClient.get(`${BASE_URL}/dashboard`),

  // Quality Standards
  getStandards: (params = {}) => apiClient.get(`${BASE_URL}/standards`, { params }),
  getStandard: (id) => apiClient.get(`${BASE_URL}/standards/${id}`),
  createStandard: (data) => apiClient.post(`${BASE_URL}/standards`, data),
  updateStandard: (id, data) => apiClient.put(`${BASE_URL}/standards/${id}`, data),
  deleteStandard: (id) => apiClient.delete(`${BASE_URL}/standards/${id}`),
  getStandardsStatistics: () => apiClient.get(`${BASE_URL}/standards/statistics`),
  getStandardsDueForReview: () => apiClient.get(`${BASE_URL}/standards/due-for-review`),
  updateStandardStatus: (id, status) => apiClient.put(`${BASE_URL}/standards/${id}/status`, { status }),

  // Audits
  getAudits: (params = {}) => apiClient.get(`${BASE_URL}/audits`, { params }),
  getAudit: (id) => apiClient.get(`${BASE_URL}/audits/${id}`),
  createAudit: (data) => apiClient.post(`${BASE_URL}/audits`, data),
  updateAudit: (id, data) => apiClient.put(`${BASE_URL}/audits/${id}`, data),
  deleteAudit: (id) => apiClient.delete(`${BASE_URL}/audits/${id}`),
  getAuditsStatistics: () => apiClient.get(`${BASE_URL}/audits/statistics`),
  getUpcomingAudits: () => apiClient.get(`${BASE_URL}/audits/upcoming`),
  getOverdueAudits: () => apiClient.get(`${BASE_URL}/audits/overdue`),
  startAudit: (id) => apiClient.post(`${BASE_URL}/audits/${id}/start`),
  completeAudit: (id, data) => apiClient.post(`${BASE_URL}/audits/${id}/complete`, data),
  updateAuditStatus: (id, status) => apiClient.put(`${BASE_URL}/audits/${id}/status`, { status }),

  // Incidents
  getIncidents: (params = {}) => apiClient.get(`${BASE_URL}/incidents`, { params }),
  getIncident: (id) => apiClient.get(`${BASE_URL}/incidents/${id}`),
  createIncident: (data) => apiClient.post(`${BASE_URL}/incidents`, data),
  updateIncident: (id, data) => apiClient.put(`${BASE_URL}/incidents/${id}`, data),
  deleteIncident: (id) => apiClient.delete(`${BASE_URL}/incidents/${id}`),
  getIncidentsStatistics: () => apiClient.get(`${BASE_URL}/incidents/statistics`),
  getCriticalIncidents: () => apiClient.get(`${BASE_URL}/incidents/critical`),
  getIncidentsRequiringFollowUp: () => apiClient.get(`${BASE_URL}/incidents/requiring-follow-up`),
  getOverdueFollowUp: () => apiClient.get(`${BASE_URL}/incidents/overdue-follow-up`),
  assignIncident: (id, assigneeId) => apiClient.post(`${BASE_URL}/incidents/${id}/assign`, { assigned_to: assigneeId }),
  resolveIncident: (id, data) => apiClient.post(`${BASE_URL}/incidents/${id}/resolve`, data),
  closeIncident: (id, data) => apiClient.post(`${BASE_URL}/incidents/${id}/close`, data),
  updateIncidentStatus: (id, status) => apiClient.put(`${BASE_URL}/incidents/${id}/status`, { status }),

  // Compliance Records
  getComplianceRecords: (params = {}) => apiClient.get(`${BASE_URL}/compliance-records`, { params }),
  getComplianceRecord: (id) => apiClient.get(`${BASE_URL}/compliance-records/${id}`),
  createComplianceRecord: (data) => apiClient.post(`${BASE_URL}/compliance-records`, data),
  updateComplianceRecord: (id, data) => apiClient.put(`${BASE_URL}/compliance-records/${id}`, data),
  deleteComplianceRecord: (id) => apiClient.delete(`${BASE_URL}/compliance-records/${id}`),
  getComplianceStatistics: () => apiClient.get(`${BASE_URL}/compliance-records/statistics`),
  getNonCompliantRecords: () => apiClient.get(`${BASE_URL}/compliance-records/non-compliant`),
  getOverdueComplianceRecords: () => apiClient.get(`${BASE_URL}/compliance-records/overdue`),
  getDueForAssessment: () => apiClient.get(`${BASE_URL}/compliance-records/due-for-assessment`),
  updateComplianceStatus: (id, data) => apiClient.put(`${BASE_URL}/compliance-records/${id}/compliance-status`, data),
  updateComplianceRecordStatus: (id, status) => apiClient.put(`${BASE_URL}/compliance-records/${id}/status`, { status }),
  scheduleNextAssessment: (id, date) => apiClient.post(`${BASE_URL}/compliance-records/${id}/schedule-next-assessment`, { next_assessment_date: date }),

  // Training Records
  getTrainingRecords: (params = {}) => apiClient.get(`${BASE_URL}/training-records`, { params }),
  getTrainingRecord: (id) => apiClient.get(`${BASE_URL}/training-records/${id}`),
  createTrainingRecord: (data) => apiClient.post(`${BASE_URL}/training-records`, data),
  updateTrainingRecord: (id, data) => apiClient.put(`${BASE_URL}/training-records/${id}`, data),
  deleteTrainingRecord: (id) => apiClient.delete(`${BASE_URL}/training-records/${id}`),
  getTrainingStatistics: () => apiClient.get(`${BASE_URL}/training-records/statistics`),
  getUpcomingTrainings: () => apiClient.get(`${BASE_URL}/training-records/upcoming`),
  getOverdueTrainings: () => apiClient.get(`${BASE_URL}/training-records/overdue`),
  getMandatoryTrainings: () => apiClient.get(`${BASE_URL}/training-records/mandatory`),
  getCertificationTrainings: () => apiClient.get(`${BASE_URL}/training-records/certification`),
  startTraining: (id) => apiClient.post(`${BASE_URL}/training-records/${id}/start`),
  completeTraining: (id, data) => apiClient.post(`${BASE_URL}/training-records/${id}/complete`, data),
  updateTrainingStatus: (id, status) => apiClient.put(`${BASE_URL}/training-records/${id}/status`, { status }),
  enrollStaffInTraining: (id, staffIds) => apiClient.post(`${BASE_URL}/training-records/${id}/enroll-staff`, { staff_ids: staffIds }),

  // Staff Training
  getStaffTrainings: (params = {}) => apiClient.get(`${BASE_URL}/staff-training`, { params }),
  getStaffTraining: (id) => apiClient.get(`${BASE_URL}/staff-training/${id}`),
  createStaffTraining: (data) => apiClient.post(`${BASE_URL}/staff-training`, data),
  updateStaffTraining: (id, data) => apiClient.put(`${BASE_URL}/staff-training/${id}`, data),
  deleteStaffTraining: (id) => apiClient.delete(`${BASE_URL}/staff-training/${id}`),
  getStaffTrainingStatistics: () => apiClient.get(`${BASE_URL}/staff-training/statistics`),
  getExpiredCertifications: () => apiClient.get(`${BASE_URL}/staff-training/expired-certifications`),
  getExpiringCertifications: (days = 30) => apiClient.get(`${BASE_URL}/staff-training/expiring-certifications`, { params: { days } }),
  getStaffTrainingHistory: (staffId) => apiClient.get(`${BASE_URL}/staff-training/staff/${staffId}/history`),
  getTrainingParticipants: (trainingId) => apiClient.get(`${BASE_URL}/staff-training/training/${trainingId}/participants`),
  updateStaffTrainingStatus: (id, status) => apiClient.put(`${BASE_URL}/staff-training/${id}/status`, { status }),
  completeStaffTraining: (id, data) => apiClient.post(`${BASE_URL}/staff-training/${id}/complete`, data),
  renewCertification: (id, expiryDate) => apiClient.post(`${BASE_URL}/staff-training/${id}/renew-certification`, { certification_expiry: expiryDate }),
  revokeCertification: (id, notes) => apiClient.post(`${BASE_URL}/staff-training/${id}/revoke-certification`, { notes }),

  // Reports
  generateReport: (filters = {}) => apiClient.post(`${BASE_URL}/reports/generate`, filters),

  // Export
  exportStandards: (format = 'excel') => apiClient.get(`${BASE_URL}/standards/export`, { params: { format } }),
  exportAudits: (format = 'excel') => apiClient.get(`${BASE_URL}/audits/export`, { params: { format } }),
  exportIncidents: (format = 'excel') => apiClient.get(`${BASE_URL}/incidents/export`, { params: { format } }),
  exportComplianceRecords: (format = 'excel') => apiClient.get(`${BASE_URL}/compliance-records/export`, { params: { format } }),
  exportTrainingRecords: (format = 'excel') => apiClient.get(`${BASE_URL}/training-records/export`, { params: { format } }),
  exportStaffTrainings: (format = 'excel') => apiClient.get(`${BASE_URL}/staff-training/export`, { params: { format } })
}

// Helper functions for common operations
export const qualityAssuranceHelpers = {
  // Format data for API calls
  formatStandardData: (data) => ({
    name: data.name,
    code: data.code,
    description: data.description,
    category: data.category,
    priority: data.priority,
    status: data.status,
    requirements: data.requirements,
    compliance_criteria: data.compliance_criteria,
    effective_date: data.effective_date,
    review_date: data.review_date
  }),

  formatAuditData: (data) => ({
    title: data.title,
    description: data.description,
    type: data.type,
    scope: data.scope,
    standard_id: data.standard_id,
    auditor_id: data.auditor_id,
    department_id: data.department_id,
    planned_date: data.planned_date,
    audit_team: data.audit_team
  }),

  formatIncidentData: (data) => ({
    title: data.title,
    description: data.description,
    type: data.type,
    severity: data.severity,
    assigned_to: data.assigned_to,
    department_id: data.department_id,
    patient_id: data.patient_id,
    staff_id: data.staff_id,
    incident_date: data.incident_date,
    immediate_action: data.immediate_action,
    requires_follow_up: data.requires_follow_up,
    follow_up_date: data.follow_up_date
  }),

  formatComplianceRecordData: (data) => ({
    standard_id: data.standard_id,
    department_id: data.department_id,
    staff_id: data.staff_id,
    compliance_status: data.compliance_status,
    assessment_date: data.assessment_date,
    next_assessment_date: data.next_assessment_date,
    assessment_notes: data.assessment_notes,
    evidence: data.evidence,
    gaps: data.gaps,
    action_plan: data.action_plan,
    priority: data.priority,
    target_completion_date: data.target_completion_date
  }),

  formatTrainingRecordData: (data) => ({
    title: data.title,
    description: data.description,
    type: data.type,
    category: data.category,
    delivery_method: data.delivery_method,
    instructor_id: data.instructor_id,
    department_id: data.department_id,
    scheduled_date: data.scheduled_date,
    duration: data.duration,
    max_participants: data.max_participants,
    learning_objectives: data.learning_objectives,
    assessment_criteria: data.assessment_criteria,
    certification_required: data.certification_required,
    certification_expiry: data.certification_expiry
  }),

  formatStaffTrainingData: (data) => ({
    staff_id: data.staff_id,
    training_id: data.training_id,
    status: data.status,
    enrollment_date: data.enrollment_date,
    score: data.score,
    result: data.result,
    feedback: data.feedback,
    assessment_results: data.assessment_results,
    notes: data.notes
  }),

  // Parse API responses
  parseStandardResponse: (response) => ({
    id: response.id,
    name: response.name,
    code: response.code,
    description: response.description,
    category: response.category,
    priority: response.priority,
    status: response.status,
    requirements: response.requirements,
    compliance_criteria: response.compliance_criteria,
    effective_date: response.effective_date,
    review_date: response.review_date,
    compliance_rate: response.compliance_rate,
    days_until_review: response.days_until_review,
    creator: response.creator,
    updater: response.updater,
    created_at: response.created_at,
    updated_at: response.updated_at
  }),

  parseAuditResponse: (response) => ({
    id: response.id,
    title: response.title,
    description: response.description,
    type: response.type,
    scope: response.scope,
    status: response.status,
    standard: response.standard,
    auditor: response.auditor,
    department: response.department,
    planned_date: response.planned_date,
    start_date: response.start_date,
    end_date: response.end_date,
    audit_team: response.audit_team,
    findings: response.findings,
    recommendations: response.recommendations,
    overall_rating: response.overall_rating,
    summary: response.summary,
    attachments: response.attachments,
    duration: response.duration,
    progress: response.progress,
    rating_color: response.rating_color,
    creator: response.creator,
    updater: response.updater,
    created_at: response.created_at,
    updated_at: response.updated_at
  }),

  parseIncidentResponse: (response) => ({
    id: response.id,
    incident_number: response.incident_number,
    title: response.title,
    description: response.description,
    type: response.type,
    severity: response.severity,
    status: response.status,
    reporter: response.reporter,
    assignee: response.assignee,
    department: response.department,
    patient: response.patient,
    staff: response.staff,
    incident_date: response.incident_date,
    reported_date: response.reported_date,
    resolved_date: response.resolved_date,
    immediate_action: response.immediate_action,
    root_cause: response.root_cause,
    corrective_action: response.corrective_action,
    preventive_action: response.preventive_action,
    witnesses: response.witnesses,
    attachments: response.attachments,
    requires_follow_up: response.requires_follow_up,
    follow_up_date: response.follow_up_date,
    follow_up_notes: response.follow_up_notes,
    resolution_time: response.resolution_time,
    severity_color: response.severity_color,
    status_color: response.status_color,
    creator: response.creator,
    updater: response.updater,
    created_at: response.created_at,
    updated_at: response.updated_at
  }),

  parseComplianceRecordResponse: (response) => ({
    id: response.id,
    standard: response.standard,
    department: response.department,
    staff: response.staff,
    compliance_status: response.compliance_status,
    assessment_date: response.assessment_date,
    next_assessment_date: response.next_assessment_date,
    assessment_notes: response.assessment_notes,
    evidence: response.evidence,
    gaps: response.gaps,
    action_plan: response.action_plan,
    priority: response.priority,
    target_completion_date: response.target_completion_date,
    status: response.status,
    assessor: response.assessor,
    days_until_assessment: response.days_until_assessment,
    compliance_status_color: response.compliance_status_color,
    status_color: response.status_color,
    priority_color: response.priority_color,
    creator: response.creator,
    updater: response.updater,
    created_at: response.created_at,
    updated_at: response.updated_at
  }),

  parseTrainingRecordResponse: (response) => ({
    id: response.id,
    title: response.title,
    description: response.description,
    type: response.type,
    category: response.category,
    delivery_method: response.delivery_method,
    instructor: response.instructor,
    department: response.department,
    scheduled_date: response.scheduled_date,
    completion_date: response.completion_date,
    duration: response.duration,
    max_participants: response.max_participants,
    participants: response.participants,
    learning_objectives: response.learning_objectives,
    assessment_criteria: response.assessment_criteria,
    status: response.status,
    pass_rate: response.pass_rate,
    feedback: response.feedback,
    attachments: response.attachments,
    certification_required: response.certification_required,
    certification_expiry: response.certification_expiry,
    duration_in_hours: response.duration_in_hours,
    completion_rate: response.completion_rate,
    status_color: response.status_color,
    type_color: response.type_color,
    creator: response.creator,
    updater: response.updater,
    created_at: response.created_at,
    updated_at: response.updated_at
  }),

  parseStaffTrainingResponse: (response) => ({
    id: response.id,
    staff: response.staff,
    training: response.training,
    status: response.status,
    enrollment_date: response.enrollment_date,
    completion_date: response.completion_date,
    score: response.score,
    result: response.result,
    feedback: response.feedback,
    assessment_results: response.assessment_results,
    certification_date: response.certification_date,
    certification_expiry: response.certification_expiry,
    certification_valid: response.certification_valid,
    notes: response.notes,
    duration: response.duration,
    days_until_certification_expiry: response.days_until_certification_expiry,
    status_color: response.status_color,
    result_color: response.result_color,
    certification_status_color: response.certification_status_color,
    creator: response.creator,
    updater: response.updater,
    created_at: response.created_at,
    updated_at: response.updated_at
  })
}
